config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  get 'demo/index'
  get 'demo/hello'
  get 'demo/about'
  get 'demo/contact'
  get 'demo/contact_us'

  get 'try/index'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end


  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'

  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  #default route
  #get ':controller(/:action(/:id))'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :pages
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  
  layout false
  
  def index
    # render('index')
  end

  def hello
    @array = [1, 2, 3]
    @id = params['id']
    @page = params[:page]
    # redirect_to(:controller => 'demo', :action => 'index')
  end

  def about
    render('about_us')
  end

  def contact_us
    @country = params[:country]
  end

  def contact
    if['us', 'ca'].include?(params[:country])
      @phone = 'ususus'
    elsif params[:country] == 'uk'
      @phone = 'ukukuk'
    else
      @phone = 'else'
    end
    render('contact_us_solution')
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.order('position ASC')
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/controllers/try_controller.rb
class TryController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/try_helper.rb
module TryHelper
end

app/views/demo/about_us.html.erb
<h1>This is the about us page.</h1>

<br />

<%= link_to('Contact us', {:action => 'contact_us', :country => 'us'}) %>

<br />

<%= link_to('index page', {:action => 'index'}) %>

<br />

<%= link_to('Contact us solution', {:action => 'contact', :country => 'uk'}) %>

app/views/demo/contact_us.html.erb
<h1>This is the contact us page.</h1>

<br />

<% if @country == "us" %>
   <p>I'm in US</p>
<% elsif @country == "uk" %>
    <p>I'm in UK</p>
<% else %>
    <p>I'm in else where</p>
<% end %>

<br />

<%= link_to('About us', {:action => 'about'}) %>

app/views/demo/contact_us_solution.html.erb
<%= @phone %>

<%= link_to('About us', {:action => 'about'}) %>

app/views/demo/hello.html.erb
<h1>This is the hello page.</h1>

<%= 1+1 %>

<br />

<% target = 'world' %>
<%= "Hello #{target}" %>

<br />

<% @array.each do |n| %>
    <p><%= n %></p>
<% end %>

<br />

<%= link_to('index page', {:action => 'index'}) %>

<br />

ID: <%= @id %><br />
ID: <%= params[:id] %><br />

Page: <%= @page %><br />
Next page: <%= @page.to_i + 1 %><br />

app/views/demo/index.html.erb
<h1>Welcome to EEEEE ValetBike.</h1>

<a href='/demo/hello'>Hello Page 1</a><br />
<%= link_to('Hello page 2', {:action => 'hello'}) %>

<br />

<%= link_to('Hello with parameters', {:action => 'hello', :page => 5, :id => 20}) %>

<br />

<%= link_to('All subjects', subjects_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/delete.html.erb
<h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/subjects/delete.html.erb
<h1>Subjects#delete</h1>
<p>Find me in app/views/subjects/delete.html.erb</p>

app/views/subjects/edit.html.erb
<h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>

app/views/subjects/index.html.erb
<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= subject.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", '#', :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<h1>Subjects#new</h1>
<p>Find me in app/views/subjects/new.html.erb</p>

app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>

app/views/try/index.html.erb
<h1>Try#index</h1>
<p>Find me in app/views/try/index.html.erb</p>